services:
  construction-app-ui:
    build: ./
    image: construction-app-ui.image
    container_name: construction-app-ui.container
    ports:
      - 3000:5173

    networks:
      - construction-app-ui.network

networks:
  construction-app-ui.network:
    name: construction-app-ui.network
    driver: bridge
